package com.securemsg.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * User — JPA entity mapped to the `users` table in MySQL.
 *
 * Fields:
 *   id          — auto-generated primary key
 *   username    — unique login name
 *   email       — unique email address
 *   password    — stored as plaintext (college demo scope)
 *   role        — USER or ADMIN
 *   enabled     — admin can disable accounts
 *   createdAt   — registration timestamp
 *   publicKey   — RSA-2048 public key, Base64-encoded (shareable)
 *   privateKey  — RSA-2048 private key, Base64-encoded (NEVER returned via API)
 *
 * RSA key notes:
 *   - Both keys are generated by RSAService at registration time.
 *   - publicKey is included in UserDTO (safe to share with other users
 *     so they can encrypt messages addressed to this user).
 *   - privateKey is stored in the DB only. It is loaded server-side
 *     during decryption and NEVER included in any DTO or API response.
 */
@Entity
@Table(name = "users")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Unique username used for login.
     * Cannot be null; must be unique across the system.
     */
    @Column(name = "username", nullable = false, unique = true, length = 50)
    private String username;

    /**
     * Unique email address for the user.
     * Cannot be null; must be unique across the system.
     */
    @Column(name = "email", nullable = false, unique = true, length = 100)
    private String email;

    /**
     * User password stored as plaintext.
     * This is a deliberate simplification for this college project.
     * In a production system a password hashing algorithm would be used,
     * but that would introduce a second cryptographic algorithm (e.g. bcrypt)
     * which is outside the RSA-only scope of this project.
     */
    @Column(name = "password", nullable = false, length = 255)
    private String password;

    /**
     * Role-based access control.
     * USER  — standard registered user
     * ADMIN — administrator with management privileges
     * Default value is set in the service layer on registration.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "role", nullable = false, length = 10)
    private Role role;

    /**
     * Whether the account is active.
     * An admin can set this to false to disable a user's access.
     * Defaults to true on registration.
     */
    @Column(name = "enabled", nullable = false)
    private boolean enabled;

    /**
     * Timestamp of when the user registered.
     * Set automatically in the service layer before saving.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * RSA-2048 public key — Base64-encoded X.509 format.
     *
     * Generated by RSAService.generateKeyPair() at registration.
     * Stored as TEXT in MySQL (Base64 RSA-2048 public key ≈ 392 chars).
     *
     * SAFE TO SHARE: included in UserDTO so other users can
     * select this user as a recipient and encrypt messages for them.
     */
    @Column(name = "public_key", columnDefinition = "TEXT", nullable = true)
    private String publicKey;

    /**
     * RSA-2048 private key — Base64-encoded PKCS#8 format.
     *
     * Generated by RSAService.generateKeyPair() at registration.
     * Stored as TEXT in MySQL (Base64 RSA-2048 private key ≈ 1728 chars).
     *
     * *** SECURITY RULE ***
     * This field MUST NEVER be:
     *   - Included in any DTO
     *   - Returned through any REST API endpoint
     *   - Logged anywhere in the application
     *
     * It is accessed server-side ONLY inside MessageService.decryptMessage()
     * via RSAService.decrypt(), and used for a single decryption operation.
     */
    @Column(name = "private_key", columnDefinition = "TEXT", nullable = true)
    private String privateKey;

    /**
     * Role enum — defines the two access levels in the system.
     */
    public enum Role {
        USER,
        ADMIN
    }
}
